language: objective-c
osx_image: beta-xcode6.3

before_install:
 - git submodule update --init --recursive
 - brew update
 - brew install carthage
 - carthage update --platform ios --verbose --configuration Debug
script: "rake"
